apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-chat
spec:
  rules:
    - host: ollama-chat.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-chat
                port:
                  number: 80
